package io.ahimsa.ahimsa_app.core;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wirebulletin.proto

public final class WireBulletinProtos {
    private WireBulletinProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface WireBulletinOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required uint32 version = 1;
        /**
         * <code>required uint32 version = 1;</code>
         */
        boolean hasVersion();
        /**
         * <code>required uint32 version = 1;</code>
         */
        int getVersion();

        // optional string topic = 2;
        /**
         * <code>optional string topic = 2;</code>
         */
        boolean hasTopic();
        /**
         * <code>optional string topic = 2;</code>
         */
        java.lang.String getTopic();
        /**
         * <code>optional string topic = 2;</code>
         */
        com.google.protobuf.ByteString
        getTopicBytes();

        // optional string message = 3;
        /**
         * <code>optional string message = 3;</code>
         */
        boolean hasMessage();
        /**
         * <code>optional string message = 3;</code>
         */
        java.lang.String getMessage();
        /**
         * <code>optional string message = 3;</code>
         */
        com.google.protobuf.ByteString
        getMessageBytes();
    }
    /**
     * Protobuf type {@code WireBulletin}
     */
    public static final class WireBulletin extends
            com.google.protobuf.GeneratedMessage
            implements WireBulletinOrBuilder {
        // Use WireBulletin.newBuilder() to construct.
        private WireBulletin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private WireBulletin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final WireBulletin defaultInstance;
        public static WireBulletin getDefaultInstance() {
            return defaultInstance;
        }

        public WireBulletin getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private WireBulletin(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            version_ = input.readUInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            topic_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            message_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return WireBulletinProtos.internal_static_WireBulletin_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return WireBulletinProtos.internal_static_WireBulletin_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            WireBulletinProtos.WireBulletin.class, WireBulletinProtos.WireBulletin.Builder.class);
        }

        public static com.google.protobuf.Parser<WireBulletin> PARSER =
                new com.google.protobuf.AbstractParser<WireBulletin>() {
                    public WireBulletin parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new WireBulletin(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<WireBulletin> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required uint32 version = 1;
        public static final int VERSION_FIELD_NUMBER = 1;
        private int version_;
        /**
         * <code>required uint32 version = 1;</code>
         */
        public boolean hasVersion() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 version = 1;</code>
         */
        public int getVersion() {
            return version_;
        }

        // optional string topic = 2;
        public static final int TOPIC_FIELD_NUMBER = 2;
        private java.lang.Object topic_;
        /**
         * <code>optional string topic = 2;</code>
         */
        public boolean hasTopic() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string topic = 2;</code>
         */
        public java.lang.String getTopic() {
            java.lang.Object ref = topic_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    topic_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string topic = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTopicBytes() {
            java.lang.Object ref = topic_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                topic_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string message = 3;
        public static final int MESSAGE_FIELD_NUMBER = 3;
        private java.lang.Object message_;
        /**
         * <code>optional string message = 3;</code>
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string message = 3;</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string message = 3;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            version_ = 0;
            topic_ = "";
            message_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasVersion()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeUInt32(1, version_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getTopicBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, version_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getTopicBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static WireBulletinProtos.WireBulletin parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static WireBulletinProtos.WireBulletin parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static WireBulletinProtos.WireBulletin parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static WireBulletinProtos.WireBulletin parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static WireBulletinProtos.WireBulletin parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static WireBulletinProtos.WireBulletin parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static WireBulletinProtos.WireBulletin parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static WireBulletinProtos.WireBulletin parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static WireBulletinProtos.WireBulletin parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static WireBulletinProtos.WireBulletin parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(WireBulletinProtos.WireBulletin prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code WireBulletin}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements WireBulletinProtos.WireBulletinOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return WireBulletinProtos.internal_static_WireBulletin_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return WireBulletinProtos.internal_static_WireBulletin_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                WireBulletinProtos.WireBulletin.class, WireBulletinProtos.WireBulletin.Builder.class);
            }

            // Construct using WireBulletinProtos.WireBulletin.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                version_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                topic_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return WireBulletinProtos.internal_static_WireBulletin_descriptor;
            }

            public WireBulletinProtos.WireBulletin getDefaultInstanceForType() {
                return WireBulletinProtos.WireBulletin.getDefaultInstance();
            }

            public WireBulletinProtos.WireBulletin build() {
                WireBulletinProtos.WireBulletin result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public WireBulletinProtos.WireBulletin buildPartial() {
                WireBulletinProtos.WireBulletin result = new WireBulletinProtos.WireBulletin(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.version_ = version_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.topic_ = topic_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof WireBulletinProtos.WireBulletin) {
                    return mergeFrom((WireBulletinProtos.WireBulletin)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(WireBulletinProtos.WireBulletin other) {
                if (other == WireBulletinProtos.WireBulletin.getDefaultInstance()) return this;
                if (other.hasVersion()) {
                    setVersion(other.getVersion());
                }
                if (other.hasTopic()) {
                    bitField0_ |= 0x00000002;
                    topic_ = other.topic_;
                    onChanged();
                }
                if (other.hasMessage()) {
                    bitField0_ |= 0x00000004;
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasVersion()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                WireBulletinProtos.WireBulletin parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (WireBulletinProtos.WireBulletin) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            // required uint32 version = 1;
            private int version_ ;
            /**
             * <code>required uint32 version = 1;</code>
             */
            public boolean hasVersion() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required uint32 version = 1;</code>
             */
            public int getVersion() {
                return version_;
            }
            /**
             * <code>required uint32 version = 1;</code>
             */
            public Builder setVersion(int value) {
                bitField0_ |= 0x00000001;
                version_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required uint32 version = 1;</code>
             */
            public Builder clearVersion() {
                bitField0_ = (bitField0_ & ~0x00000001);
                version_ = 0;
                onChanged();
                return this;
            }

            // optional string topic = 2;
            private java.lang.Object topic_ = "";
            /**
             * <code>optional string topic = 2;</code>
             */
            public boolean hasTopic() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>optional string topic = 2;</code>
             */
            public java.lang.String getTopic() {
                java.lang.Object ref = topic_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    topic_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string topic = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTopicBytes() {
                java.lang.Object ref = topic_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    topic_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string topic = 2;</code>
             */
            public Builder setTopic(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                topic_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string topic = 2;</code>
             */
            public Builder clearTopic() {
                bitField0_ = (bitField0_ & ~0x00000002);
                topic_ = getDefaultInstance().getTopic();
                onChanged();
                return this;
            }
            /**
             * <code>optional string topic = 2;</code>
             */
            public Builder setTopicBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                topic_ = value;
                onChanged();
                return this;
            }

            // optional string message = 3;
            private java.lang.Object message_ = "";
            /**
             * <code>optional string message = 3;</code>
             */
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>optional string message = 3;</code>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string message = 3;</code>
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string message = 3;</code>
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string message = 3;</code>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000004);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }
            /**
             * <code>optional string message = 3;</code>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:WireBulletin)
        }

        static {
            defaultInstance = new WireBulletin(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:WireBulletin)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_WireBulletin_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_WireBulletin_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\022wirebulletin.proto\"?\n\014WireBulletin\022\017\n\007" +
                        "version\030\001 \002(\r\022\r\n\005topic\030\002 \001(\t\022\017\n\007message\030" +
                        "\003 \001(\tB\024B\022WireBulletinProtos"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_WireBulletin_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_WireBulletin_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_WireBulletin_descriptor,
                                new java.lang.String[] { "Version", "Topic", "Message", });
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
